services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=reminders
    ports:
      - "15432:15432"
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=15432
      - DB_NAME=reminders
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=1234
volumes:
  postgres_data: