telegram:
  bot:
    token: 7783739105:AAEqK4xTNb1aIv7BjeGLNtnCZ7mcZUJE9LM
    start-message: |
      🤖🚀 Привет! 🤖🚀
      Я чат-бот который напомнит тебе все то, что ты забыл!!! 
      Используй следующие команды:
      /registration - регистрация
      /login - войти.
    login-message: |
      🤖🚀 Ты успешно вошел в системе! 🤖🚀
      Используй следующие команды:
      /find - найти напоминание.
      /new - создать напоминание.
      /update - обновить напоминание.
      /delete - удалить напоминание.