spring:
  application:
    name: reminders
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:reminders}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false