spring:
  application:
    name: reminders
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    url: jdbc:postgresql://db:5432/${DB_NAME}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

