telegram:
  token: 7783739105:AAEqK4xTNb1aIv7BjeGLNtnCZ7mcZUJE9LM
  command:
    registration: /registration
    login: /login
    find: /find
    create: /create
    update: /update
    delete: /delete
  message:
    start: |
      🤖🚀 Привет! 🤖🚀
      Я чат-бот который напомнит тебе все то, что ты забыл!!! 
      Используй следующие команды:
      /registration - регистрация
      /login - войти.
    login: |
      🤖🚀 Ты успешно вошел в системе! 🤖🚀
      Используй следующие команды:
      /find - найти напоминание.
      /new - создать напоминание.
      /update - обновить напоминание.
      /delete - удалить напоминание.
    logged: |
      Ты зарегистрирован в системе! 
      Используй команду: /login
    reminder: "⏰ Напоминание: %s\n📝 Описание: %s\n⏳ Время: %s\n\uD83D\uDD25 Приоритет: %s \n\uD83C\uDFC1 Выполнено: %s"